### ISSUE TITLE
Unexpected return object from 'stripe.createToken()'

### ISSUE THREAD

**Issue by nating** [expo/stripe-expo#15]
It seems that the .createToken() method is returning a different object than [expected](https://stripe.com/docs/api/node#token_object). Instead, it returns the entire response from the fetch to Stripe. The examples from the README.md access the 'id' attribute of the returned object, of which there is none. 

I think that the solution is for the '_createTokenHelper()' function not to return the entire response from Stripe.

I'm going to make a quick pull-request to change it, but if this is actually the intended functionality of the 'createToken()' & '_createTokenHelper()' functions, don't mind me! 😊

**Comment by nating** [comment]
Haven't got to change it round just yet, but should have it by later on.

**Comment by nating** [comment]
I think either the '_createTokenHelper()' function should return the json of the response, like this:
```javascript
function _createTokenHelper(details, key) {
  const formBody = FORMURLENCODED(details);
  var response = fetch(STRIPE_URL + 'tokens', {
    method: 'post',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/x-www-form-urlencoded',
      'Authorization': 'Bearer ' + key
    },
    body: formBody
  });
  return response.json(); //<-- (Return this instead of the response itself)
}
```

Or the documentation should be updated to say that this is how you get the user's Stripe token out of what's returned from 'createToken()'.
```javascript
var information = {
          card: {
              number: this.state.cardNumber,
              exp_month: this.state.cardExpiryMonth,
              exp_year: this.state.cardExpiryYear,
              cvc: this.state.cardCVC
          }
        }
        
    var response = await stripe.createToken(information);
    response.json().then(json => {
      //Here 'json' is the object with the token inside
      //And 'json.id' is the stripe token for the user 
    });
```

I'm not sure which way you'd like to implement things for it, so I don't think I'll make a pull request and just let you do it whatever way you would like it! 😎

**Comment by jeff-da** [comment]
Hey Geoff! Thanks so much for bringing this issue to my intention. I had intended for the JSON of the fetch to be returned, but I made a last-second change that caused the fetch to be returned instead.

It should be fixed now. Let me know if you run into any issues!
