### ISSUE TITLE
Do I need to detach my expo project to make this API work?

### ISSUE THREAD

**Issue by sbkl** [expo/stripe-expo#18]
Hi,

Thinking to switch my react-native apps to expo and the only blocking point I have today is about payment. According to the payment documentation from your website, I need to detach a project to implement it.

Is this library working without detaching the related expo project?

Also, if I need to detach a project, can I still use expo functionalities to publish my app to store and/or use push notifications for instance?

How can I be aware once expo support full implementation of Stripe payments?

Thanks and regards,

**Comment by jeff-da** [comment]
Hey sbkl!

Thanks for the great question! This module is separate from the native payments module - while they both allow for Stripe integration, this module purely implements JavaScript. This means that you can use the module on both iOS and Android without detaching.

Please note that it's important not to rely on the Expo docs here, but rather the readme in this repository :)

**Comment by sbkl** [comment]
Thanks for answering. Just tried it with the token creation example of the doc but I get empty answer from the createToken call:

Code
`    
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

var stripe = require('stripe-client')('test publishable key I use normally');

export default class App extends React.Component {

  componentDidMount() {

    let card = stripe.createToken({
      card: {
        "number": '4242424242424242',
        "exp_month": 12,
        "exp_year": 2018,
        "cvc": '123'
      }
    });
    console.log(card);
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
      </View>
    );
  }
}
`
Response

```
Promise {
  "_40": 0,
  "_55": null,
  "_65": 0,
  "_72": null,
}
```

Any idea?
