### ISSUE TITLE
Current release (1.1.3) does not include important fix

### ISSUE THREAD

**Issue by cjbutcher** [expo/stripe-expo#22]
Pull request #20 fixes an important bug, but it is not being included when package.json reads:

"stripe-client": "^1.1.3"

Instead to get it one has to install the client using:

"stripe-client": "github:expo/stripe-expo#master"

I'm no expert in how to resolve this... perhaps tag a new release?

**Comment by slorber** [comment]
Hi,

I can confirm the last release published does not include this important fix.

I think latest Expo / RN release is unable to use this project, as I started getting JSON parsing errors recently, probably after upgrading to Expo 26.

Using the code of the mentionned PR does solve the problem.


Please someone of the Expo team publish a new release, there's no code change to do, just publish the existing code already on master.

cc @brentvatne @terribleben  don't know who's responsible of this package as @jeff-da is not Expo anymore

**Comment by jeff-da** [comment]
I went ahead and updated the npm package to 1.1.5 (which includes the pull requests). Let me know if there are any other issues!

**Comment by slorber** [comment]
thanks @jeff-da nothing else to do for me
